### ISSUE TITLE
🖼 Image alpha cutting other images

### ISSUE THREAD

**Issue by anynoise00** [katharostech/bevy_retro#12]
Here is a print of what is happening:
![image](https://user-images.githubusercontent.com/51768996/116641908-0f083b00-a944-11eb-902a-e67616a3247f.png)

**Comment by zicklag** [comment]
That happens when you have two sprites on the same Z layer that over-lap each-other. If you make sure that one of the radishes has a higher or lower Z position, then it will fix that issue.

I'm not sure if I could fix it so that this doesn't happen, but there would be no way to know which sprite to put on top even if I did, so the one that would end up on top would be random. :thinking:

**Comment by anynoise00** [comment]
Thanks for the response, I'll try switching the Z layers then.

But I hope that this issue really is a bug, I never though of using two different Z layers for two players or two entities in the same "draw layer", and I also don't know how I would handle "draw layers", because I was thinking of using some constants for them, like: -1: background, 0: player, 1: foreground, etc.

For the issue of not knowing what sprite would end on top, I've used Godot/Unity in the past, and I think that there, the sprites are drawn based on who is on top of the tree, or based on what sprite was instanced first. Would it be expensive to keep track of what sprite is instanced first and ordering the render using that AND the Z layer?

Sorry for the late response.

**Comment by zicklag** [comment]
Yeah, that makes sense, you've convinced me. We've got to find a way to fix it. :)

> Would it be expensive to keep track of what sprite is instanced first and ordering the render using that AND the Z layer?

:thinking: I think I could sort by the entity ID, but I'm not sure that would _guarantee_ that they would be in the proper order. If there were times where they didn't show up in the order they were spawned do you think that would be tolerable if there wasn't the clipping issue?

> Sorry for the late response.

No problem. 🙂

**Comment by zicklag** [comment]
@anynoise00 This should be fixed now! Sprites are now additionally sorted by their entity ID, which should correspond to the order that the entity was spawned.

Let me know if you have any other problems.
