### ISSUE TITLE
Can't build a minimal project

### ISSUE THREAD

**Issue by Carbone13** [katharostech/bevy_retro#15]
Hi, I am really new to rust & Bevy, I tried to import the Bevy Retro plugin but I am unable to build it
My depencies are setup as that :

```
[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_retro = { git = "https://github.com/katharostech/bevy_retro.git" }
```

However when trying to build (=running `cargo run`), this is what I get :
![Screenshot_5](https://user-images.githubusercontent.com/38987429/118413383-6544e000-b69f-11eb-9c35-a959c47a7402.jpg)

Any ideas of what I am doing wrong ?

**Comment by zicklag** [comment]
Hey there! Sorry about that, that's my fault! I had forgotten to update the dependency so it would properly work outside of this repository.

I just pushed a fix. You should be able to run `cargo update` and then `cargo build` should complete successfully. Let me know if you have any other problems!
